import { Effect } from "effect";
import type { CaptionTrack, VideoDetails } from "../../domain.js";
import { ExtractionError } from "../../errors.js";
import {
  findAll,
  findFirst,
  get,
  getArray,
  getBoolean,
  getNumber,
  getString,
  parseCount,
  text,
  textAt,
  thumbnails,
} from "../json.js";
import {
  channelUrl,
  embeddedNumber,
  handleFromUrl,
  isVerified,
  videoUrl,
} from "./common.js";

/** A caption track plus the signed URL its transcript is served from. */
export interface RawCaptionTrack extends CaptionTrack {
  readonly baseUrl: string;
}

const captionTracks = (player: unknown): ReadonlyArray<RawCaptionTrack> =>
  getArray(player, "captions.playerCaptionsTracklistRenderer.captionTracks")
    .flatMap((track) => {
      const languageCode = getString(track, "languageCode");
      const baseUrl = getString(track, "baseUrl");
      if (languageCode === undefined || baseUrl === undefined) return [];
      return [
        {
          languageCode,
          name: textAt(track, "name"),
          isAutoGenerated: getString(track, "kind") === "asr",
          isTranslatable: getBoolean(track, "isTranslatable") ?? false,
          baseUrl,
        },
      ];
    });

/**
 * Caption tracks from the first player response that carries any.
 *
 * Which client answers matters: the web client returns none when it refuses
 * playback, while the mobile clients return the full list.
 */
export const captionTracksOf = (
  players: ReadonlyArray<unknown>,
): ReadonlyArray<RawCaptionTrack> => {
  for (const player of players) {
    const tracks = captionTracks(player);
    if (tracks.length > 0) return tracks;
  }
  return [];
};

/**
 * Reads the like count.
 *
 * The button has been rewritten three times over: a legacy toggle button with a
 * short label, an accessibility string carrying the exact figure, and the
 * current view-model. The accessible label is preferred because it is the only
 * one that is not rounded.
 */
const likeCount = (next: unknown): number | undefined => {
  const segmented = findFirst(next, "segmentedLikeDislikeButtonViewModel");

  const accessible = [
    getString(
      segmented,
      "likeButtonViewModel.likeButtonViewModel.toggleButtonViewModel.toggleButtonViewModel.defaultButtonViewModel.buttonViewModel.accessibilityText",
    ),
    findFirst(segmented, "accessibilityText"),
    findFirst(next, "accessibilityText"),
  ].find((value) => typeof value === "string" && /\d/.test(value));

  const fromAccessible = embeddedNumber(accessible);
  if (fromAccessible !== undefined) return fromAccessible;

  const legacy = findAll(next, "toggleButtonRenderer")
    .map((button) =>
      getString(
        button,
        "defaultText.accessibility.accessibilityData.label",
      ),
    )
    .find((label) => label !== undefined && /like/i.test(label));

  return embeddedNumber(legacy);
};

const commentCount = (next: unknown): number | undefined => {
  const header = findFirst(next, "commentsEntryPointHeaderRenderer");
  return (
    parseCount(textAt(header, "commentCount")) ??
    embeddedNumber(textAt(header, "headerText"))
  );
};

const owner = (next: unknown) => findFirst(next, "videoOwnerRenderer");

/**
 * Builds video details from one or more `/player` responses, enriched with
 * `/next` when one was fetched.
 *
 * Several responses are merged because no single client returns everything:
 * WEB carries the microformat (publish date, category, country availability)
 * even when it refuses playback, while the mobile clients answer `OK` and carry
 * the caption list. Each field is taken from the first response that has it,
 * with the playable response leading. `/player` never carries like, comment, or
 * subscriber counts at all — those only exist on the watch page.
 */
export const extractVideoDetails = (
  players: ReadonlyArray<unknown>,
  next: unknown,
): Effect.Effect<VideoDetails, ExtractionError> =>
  Effect.gen(function* () {
    /** First defined result across the player responses, in priority order. */
    const pick = <A>(read: (player: unknown) => A | undefined): A | undefined => {
      for (const player of players) {
        const value = read(player);
        if (value !== undefined) return value;
      }
      return undefined;
    };

    const player = players[0];
    const details = pick((response) => get(response, "videoDetails"));
    const microformat = pick((response) =>
      get(response, "microformat.playerMicroformatRenderer"),
    );

    const id = getString(details, "videoId");
    if (id === undefined) {
      return yield* new ExtractionError({
        message: "Player response did not contain videoDetails.videoId",
        path: "videoDetails.videoId",
        received: getString(player, "playabilityStatus.status"),
      });
    }

    const title =
      getString(details, "title") ?? textAt(microformat, "title") ?? "";

    const ownerRenderer = owner(next);
    const canonicalBaseUrl = getString(
      ownerRenderer,
      "navigationEndpoint.browseEndpoint.canonicalBaseUrl",
    );
    const ownerProfileUrl = getString(microformat, "ownerProfileUrl");

    const channelId =
      getString(details, "channelId") ??
      getString(microformat, "externalChannelId");

    const subscriberCountText = textAt(ownerRenderer, "subscriberCountText");

    const liveNow = getBoolean(
      microformat,
      "liveBroadcastDetails.isLiveNow",
    );

    return {
      id,
      title,
      url: videoUrl(id),
      description:
        getString(details, "shortDescription") ??
        textAt(microformat, "description"),
      durationSeconds:
        getNumber(details, "lengthSeconds") ??
        getNumber(microformat, "lengthSeconds"),
      thumbnails: thumbnails(get(details, "thumbnail")),
      channel: {
        id: channelId,
        name:
          getString(details, "author") ??
          textAt(microformat, "ownerChannelName"),
        handle: handleFromUrl(canonicalBaseUrl ?? ownerProfileUrl),
        url:
          canonicalBaseUrl !== undefined
            ? `https://www.youtube.com${canonicalBaseUrl}`
            : ownerProfileUrl ??
              (channelId !== undefined ? channelUrl(channelId) : undefined),
        thumbnails: thumbnails(get(ownerRenderer, "thumbnail")),
        isVerified: isVerified(get(ownerRenderer, "badges")),
        subscriberCount: parseCount(subscriberCountText),
        subscriberCountText,
      },
      viewCount:
        getNumber(details, "viewCount") ?? getNumber(microformat, "viewCount"),
      likeCount: likeCount(next),
      commentCount: commentCount(next),
      publishedAt: getString(microformat, "publishDate"),
      uploadedAt: getString(microformat, "uploadDate"),
      publishedText: textAt(findFirst(next, "videoPrimaryInfoRenderer"), "dateText"),
      category: getString(microformat, "category"),
      keywords: getArray(details, "keywords").filter(
        (keyword): keyword is string => typeof keyword === "string",
      ),
      isLive: liveNow ?? getBoolean(details, "isLive") ?? false,
      isLiveContent: getBoolean(details, "isLiveContent") ?? false,
      isUpcoming: getBoolean(details, "isUpcoming") ?? false,
      isPrivate: getBoolean(details, "isPrivate") ?? false,
      isUnlisted: getBoolean(microformat, "isUnlisted") ?? false,
      isFamilySafe: getBoolean(microformat, "isFamilySafe"),
      allowRatings: getBoolean(details, "allowRatings"),
      captions: captionTracksOf(players).map(
        ({ baseUrl: _baseUrl, ...track }) => track,
      ),
      availableCountries: getArray(microformat, "availableCountries").filter(
        (country): country is string => typeof country === "string",
      ),
      playabilityStatus:
        getString(player, "playabilityStatus.status") ?? "UNKNOWN",
      playabilityReason:
        getString(player, "playabilityStatus.reason") ??
        text(
          get(
            player,
            "playabilityStatus.errorScreen.playerErrorMessageRenderer.subreason",
          ),
        ),
    } satisfies VideoDetails;
  });

/** Playability values that mean "try a different client" rather than "give up". */
const RETRYABLE_STATUSES = new Set([
  "LOGIN_REQUIRED",
  "UNPLAYABLE",
  "AGE_VERIFICATION_REQUIRED",
  "CONTENT_CHECK_REQUIRED",
]);

export const isRetryablePlayability = (player: unknown): boolean => {
  const status = getString(player, "playabilityStatus.status");
  return status !== undefined && RETRYABLE_STATUSES.has(status);
};

export const playabilityStatus = (player: unknown): string =>
  getString(player, "playabilityStatus.status") ?? "UNKNOWN";

export const playabilityReason = (player: unknown): string | undefined =>
  getString(player, "playabilityStatus.reason") ??
  text(
    get(
      player,
      "playabilityStatus.errorScreen.playerErrorMessageRenderer.reason",
    ),
  );
