/**
 * Public domain models.
 *
 * These are the stable surface of the library: raw Innertube renderers never
 * escape the extractors. Fields that YouTube only sometimes provides are
 * optional rather than defaulted, so callers can tell "absent" from "zero".
 */

export interface Thumbnail {
  readonly url: string;
  readonly width?: number;
  readonly height?: number;
}

/** A reference to a channel as it appears alongside another resource. */
export interface AuthorRef {
  readonly id?: string;
  readonly name?: string;
  readonly handle?: string;
  readonly url?: string;
  readonly thumbnails: ReadonlyArray<Thumbnail>;
  readonly isVerified: boolean;
}

export interface VideoSearchResult {
  readonly type: "video";
  readonly id: string;
  readonly title: string;
  readonly url: string;
  readonly description?: string;
  readonly durationSeconds?: number;
  readonly durationText?: string;
  readonly thumbnails: ReadonlyArray<Thumbnail>;
  readonly author?: AuthorRef;
  readonly publishedText?: string;
  readonly viewCount?: number;
  readonly viewCountText?: string;
  readonly isLive: boolean;
  readonly badges: ReadonlyArray<string>;
}

export interface ChannelSearchResult {
  readonly type: "channel";
  readonly id: string;
  readonly title: string;
  readonly url: string;
  readonly handle?: string;
  readonly description?: string;
  readonly thumbnails: ReadonlyArray<Thumbnail>;
  readonly subscriberCount?: number;
  readonly subscriberCountText?: string;
  readonly videoCountText?: string;
  readonly isVerified: boolean;
}

export interface PlaylistSearchResult {
  readonly type: "playlist";
  readonly id: string;
  readonly title: string;
  readonly url: string;
  readonly thumbnails: ReadonlyArray<Thumbnail>;
  readonly videoCount?: number;
  readonly author?: AuthorRef;
}

export type SearchResult =
  | VideoSearchResult
  | ChannelSearchResult
  | PlaylistSearchResult;

export interface SearchPage {
  readonly results: ReadonlyArray<SearchResult>;
  readonly estimatedResults?: number;
  /** Token for the next page, absent when the feed is exhausted. */
  readonly continuation?: string;
}

export interface CaptionTrack {
  readonly languageCode: string;
  readonly name?: string;
  readonly isAutoGenerated: boolean;
  readonly isTranslatable: boolean;
}

export interface VideoDetails {
  readonly id: string;
  readonly title: string;
  readonly url: string;
  readonly description?: string;
  readonly durationSeconds?: number;
  readonly thumbnails: ReadonlyArray<Thumbnail>;
  readonly channel: AuthorRef & {
    readonly subscriberCount?: number;
    readonly subscriberCountText?: string;
  };
  readonly viewCount?: number;
  readonly likeCount?: number;
  readonly commentCount?: number;
  /** ISO date from the microformat, when YouTube supplies one. */
  readonly publishedAt?: string;
  readonly uploadedAt?: string;
  readonly publishedText?: string;
  readonly category?: string;
  readonly keywords: ReadonlyArray<string>;
  readonly isLive: boolean;
  readonly isLiveContent: boolean;
  readonly isUpcoming: boolean;
  readonly isPrivate: boolean;
  readonly isUnlisted: boolean;
  readonly isFamilySafe?: boolean;
  readonly allowRatings?: boolean;
  readonly captions: ReadonlyArray<CaptionTrack>;
  readonly availableCountries: ReadonlyArray<string>;
  /** Playability as reported by YouTube, e.g. `"OK"`, `"LOGIN_REQUIRED"`. */
  readonly playabilityStatus: string;
  readonly playabilityReason?: string;
}

export interface TranscriptSegment {
  readonly startMs: number;
  readonly endMs: number;
  readonly startSeconds: number;
  readonly endSeconds: number;
  readonly text: string;
}

export interface Transcript {
  readonly videoId: string;
  readonly languageCode: string;
  readonly language?: string;
  readonly isAutoGenerated: boolean;
  /** Every caption track the video offers, including the one returned. */
  readonly availableLanguages: ReadonlyArray<CaptionTrack>;
  readonly segments: ReadonlyArray<TranscriptSegment>;
  /** All segments joined with spaces — the common case for downstream use. */
  readonly text: string;
}

export interface ChannelLink {
  readonly title?: string;
  readonly url?: string;
}

export interface ChannelDetails {
  readonly id: string;
  readonly title: string;
  readonly handle?: string;
  readonly url: string;
  readonly canonicalUrl?: string;
  readonly description?: string;
  readonly thumbnails: ReadonlyArray<Thumbnail>;
  readonly banner: ReadonlyArray<Thumbnail>;
  readonly subscriberCount?: number;
  readonly subscriberCountText?: string;
  readonly videoCount?: number;
  readonly videoCountText?: string;
  readonly viewCount?: number;
  readonly viewCountText?: string;
  /** Display text such as `"Joined Mar 21, 2008"`. */
  readonly joinedDateText?: string;
  readonly country?: string;
  readonly keywords: ReadonlyArray<string>;
  readonly tags: ReadonlyArray<string>;
  readonly links: ReadonlyArray<ChannelLink>;
  readonly isFamilySafe?: boolean;
  readonly isVerified: boolean;
}
